<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<?php $item = $block->getItem() ?>
<tr style="background-color: #ffffff;" bgcolor="#ffffff">
    <td colspan="6" height="5"><div style="font-size: 0; height: 0;">&nbsp;</div></td>
</tr>
<tr style="background-color: #ffffff;" bgcolor="#ffffff">
    <td>&nbsp;</td>
    <td align="left" height="35">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="60px" valign="top"><img style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 26px; color: #707582;" alt="<?php echo $block->escapeHtml($item->getName()) ?>" src="<?php echo $this->getItemImage($item);?>" width="100%"/> </td>
                <td width="10px">&nbsp;</td>
                <td>

                    <table cellpadding="0" cellspacing="0" border="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; ">
                        <tr>
                            <td style="color: #707582; font-size: 14px; height:25px!important" height="25" colspan="2">
                                <b><?php echo $block->escapeHtml($item->getName()) ?></b>
                            </td>
                        </tr>
                        <tr>
                            <td height="5" colspan="2"><div style="font-size: 0; height: 0;">&nbsp;</div></td>
                        </tr>
                        <tr style="color: #707582; font-size: 15px; line-height: 20px">
                            <td height="25" style="font-size: 14px; font-weight: bold">
                                <?php echo __("Sku");?>&nbsp;&nbsp;</td>
                            <td style="font-size: 14px; "><?php echo $block->escapeHtml($block->getSku($item)) ?></td>
                        </tr>
                        <?php if ($block->getItemOptions()): ?>
                            <?php foreach ($block->getItemOptions() as $option): ?>
                                <tr style="color: #707582; font-size: 15px; line-height: 20px">
                                    <td height="25" style="font-size: 14px; font-weight: bold"><?php echo $option['label'] ?>&nbsp;&nbsp;</td>
                                    <td style="font-size: 14px; "><?php echo nl2br($option['value']) ?></td>
                                </tr>
                            <?php endforeach; ?>
                            <tr>
                                <td colspan="2" height="3"><div style="font-size: 0; height: 0;">&nbsp;</div></td>
                            </tr>
                        <?php endif; ?>
                    </table>
                </td>
            </tr>
        </table>
    </td>

    <td valign="top" style="color: #707582; font-size: 14px; height:25px!important" align="center" height="35" >
        <?php echo $item->getQtyOrdered()*1 ?>
    </td>

    <td valign="top" style="color: #707582; font-size: 14px; height:25px!important" align="right"  height="35" >
        <?php echo /* @escapeNotVerified */  $block->formatPrice($item->getPriceInclTax(), $item->getStore()); ?>
    </td>
    <td>&nbsp;</td>
</tr>


