<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<?php if ($block->isActive()) : ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "abandonedCartBar": <?php echo $this->getConfigJs();?>

            }
        }
    </script>
<?php endif; ?>