<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<div class="cms-static-about-top">
<img src="/media/wysiwyg/about-us-bg_1.png" alt="About us" class="newsletter-bg position-absolute top-0 bottom-0 start-0 end-0 m-auto" loading="lazy">
<div class="container position-relative">
<h1 class="cta-title">Blog</h1>
</div>
</div>
<div class="container">
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper pt-5">
        <?php $iterator = 1; ?>
        <div class="row post-list">
            <?php foreach ($_postCollection as $_post): ?>
                <?php echo $block->getPostHtml($_post) ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $block->getToolbarHtml() ?>

    <script type="text/javascript">var addthis_config = {"data_track_clickback":false};</script>
    <script type="text/javascript" async src="//s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4def63cd3cf37569"></script>
    <script type="text/javascript">
        var addthis_config = {
            ui_language: "en"
        }
    </script>
<?php endif; ?>
</div>
