<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="col-lg-3 col-md-6">
<a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
    <div class="blog-item">
        <div class="blog-img">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
        <?php } ?>
        </div>
        <div class="blog-content">
            <h2 class="post-title"><?php echo $_postName; ?></h2>
            <div class="excerpt">
            <?php
            $blog_content = $block->getShorContent($_post);
            if ($blog_content !== null && $blog_content !== '') {
                
                $plainText = strip_tags($blog_content);

                $words = explode(' ', $plainText);
                $firstSevenWords = array_slice($words, 0, 12);
                $shortDescription = implode(' ', $firstSevenWords);
                echo $shortDescription;
            }
            ?>
            </div>
            <div class="blink"><span class="read-more-link">Read more ></span></div>
        </div>
    </div>
</a>
</div>
