<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $custom_stock_status = $_product->getAttributeText('custom_stock_status'); ?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php echo __('Availability') ?>">
            <label><?php echo __('Availability:') ?></label><span><?php if(!empty($custom_stock_status)){ echo $custom_stock_status; } else { echo __('In stock'); } ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php  echo __('Availability') ?>">
            <label><?php echo __('Availability:') ?></label><span><?php  echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
