<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */
/** @var \Amasty\RequestQuote\Block\Email\Items $block */
?>

<?php $quote = $block->getQuote() ?>
<?php if ($quote): ?>
    <?php
    // Get the shipping address
    $shippingAddress = $quote->getShippingAddress();
    ?>
<tr>
<td>
                <h2><?= __('Shipping Address') ?></h2>
                <p><?= $shippingAddress->format('html') ?></p>
</td>
</tr>
    <?php $items = $quote->getAllItems(); ?>
    <table class="email-items">
        <thead>
<tr>
            <th class="item-photo">
                <?= /* @noEscape */  __('Image') ?>
            </th>
            <th class="item-info" colspan="3">
                <?= /* @noEscape */  __('Items') ?>
            </th>
            <th class="item-qty">
                <?= /* @noEscape */  __('Qty') ?>
            </th>
            <th class="item-price">
                <?= /* @noEscape */  __('Price') ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($items as $item): ?>
            <?php if (!$item->getParentItem()): ?>
                <tbody>
                <?= $block->getItemHtml($item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('quote_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
