<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<?php
$item = $block->getItem();
$product = $item->getProduct();
?>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <?php if ($item->getData('column_number') != 1) : ?>
        <td width="15px">&nbsp;</td>
        <?php endif; ?>
        <td>
            <table width="100%" border="0" cellpadding="0" cellspacing="0"  style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 15px; line-height: 26px; color: #707582;">
                <tr>
                    <td align="center" height="135px" valign="bottom">
                        <img src="<?php /* @escapeNotVerified */ echo $block->getItemImage($item); ?>"/>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <b><?php /* @escapeNotVerified */ echo $product->getName(); ?></b>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <?php echo $item->getQty(); ?> X <?php echo /* @escapeNotVerified */  $block->formatPrice($item->getPriceInclTax(), $item->getStore()); ?>
                    </td>
                </tr>
            </table>
        </td>
        <?php if ($item->getData('column_number') != 3) : ?>
            <td width="15px">&nbsp;</td>
        <?php endif; ?>
    </tr>
</table>


