<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */
/**
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?php if ($block->displayBoth()): ?>
    <tr class="row-totals">
        <td style="<?= /* @noEscape */ $block->getStyle() ?>"
            class="admin__total-mark"
            colspan="<?= /* @noEscape */ $block->getColspan() ?>">
            <?= $escaper->escapeHtml($block->getExcludeTaxLabel()) ?>
        </td>
        <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="admin__total-amount">
            <?= /* @noEscape */ $block->formatPrice($block->getShippingExcludeTax()) ?>
        </td>
    </tr>
    <tr class="row-totals">
        <td style="<?= /* @noEscape */ $block->getStyle() ?>"
            class="admin__total-mark"
            colspan="<?= /* @noEscape */ $block->getColspan() ?>">
            <?= $escaper->escapeHtml($block->getIncludeTaxLabel()) ?>
        </td>
        <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="admin__total-amount">
            <?= /* @noEscape */ $block->formatPrice($block->getShippingIncludeTax()) ?>
        </td>
    </tr>
<?php elseif ($block->displayIncludeTax()): ?>
    <tr>
        <td style="<?= /* @noEscape */ $block->getStyle() ?>"
            class="admin__total-mark"
            colspan="<?= /* @noEscape */ $block->getColspan() ?>">
            <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        </td>
        <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="admin__total-amount">
            <?= /* @noEscape */ $block->formatPrice($block->getShippingIncludeTax()) ?>
        </td>
    </tr>
<?php else:?>
    <tr class="row-totals">
        <td style="<?= /* @noEscape */ $block->getStyle() ?>"
            class="admin__total-mark"
            colspan="<?= /* @noEscape */ $block->getColspan() ?>">
            <?= $escaper->escapeHtml($block->getTotal()->getTitle()) ?>
        </td>
        <td style="<?= /* @noEscape */ $block->getStyle() ?>" class="admin__total-amount">
            <?= /* @noEscape */ $block->formatPrice($block->getShippingExcludeTax()) ?>
        </td>
    </tr>
<?php endif;?>
