<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<table dir="ltr" width="100%" border="0" cellpadding="0" cellspacing="0"
       style="width: 100% !important; max-width: 100% !important; background-color: #f1f1f1" bgcolor="#f1f1f1">
    <tr>
        <td width="2%" style="width: 2%!important;">
            <div style="font-size: 0; height: 0;">&nbsp;</div>
        </td>
        <td align="center">
            <table
                    width="600"
                    cellspacing="0" cellpadding="0" border="0"
                    style="width: 100% !important; max-width: 600px !important; background-color: #FFFFFF;"
                    bgcolor="#FFFFFF" data-block-content="">
                <tr>
                    <td width="5%" style="width: 5%!important;">&nbsp;</td>
                    <td align="center">
                        <!--[if mso]>
                        <div style="font-size: 0; height: 0; line-height: 0;">&nbsp;</div><![endif]-->
                        <div>



