<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
                    </div>
                    <!--[if mso]>
                    <div style="font-size: 0; height: 0; line-height: 0">&nbsp;</div><![endif]-->
                </td>
                    <td width="5%" style="width: 5%!important;">&nbsp;</td>
                </tr>
            </table>
        </td>
        <td width="2%" style="width: 2%!important;">
            <div style="font-size: 0; height: 0;">&nbsp;</div>
        </td>
    </tr>
</table>