<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<div class="mage-magictabs mc-<?php echo $this->getTypeFilter();?>">
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php //echo $block->getAdditionalHtml() ?>
    <?php
    // if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    // } else {
    //     $viewMode = 'list';
    //     $image = 'category_page_list';
    //     $showDescription = true;
    //     $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    // }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php 
        $config     = $this->getWidgetCfg(); 
        // $width      = $config['widthImages'];
        // $height     = $config['heightImages'];
        $showCart       = $config['cart'];
        $showCompare    = $config['compare'];
        $showWishlist   = $config['wishlist'];
        $showReview     = $config['review'];
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
$ship_opt='';
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php $custom_stock_status = $_product->getAttributeText('custom_stock_status'); $ship_opt = $_product->getAttributeText('shippingoption'); ?>
                    <?php // Product Image ?>
                    <div class="images-container">
                        <?php /* ?><div class="link-view">
                             <button type="button" class="quickview"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><i class="pe-icon pe-7s-search icons"></i><?php //echo __('Quick View')?></span>
                             </button>
                        </div><?php */ ?>
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                        <div class="product-hover">
                            <?php echo $_aloHelper->getLabels($_product); ?>
                            <?php //echo $_aloHelper->getTimer($_product); ?>
                            <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php /*if($_product->getAttributeText('shippingoption')=="Free"){ ?>
                                <div class="delivery-tag"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M48 0C21.5 0 0 21.5 0 48V368c0 26.5 21.5 48 48 48H64c0 53 43 96 96 96s96-43 96-96H384c0 53 43 96 96 96s96-43 96-96h32c17.7 0 32-14.3 32-32s-14.3-32-32-32V288 256 237.3c0-17-6.7-33.3-18.7-45.3L512 114.7c-12-12-28.3-18.7-45.3-18.7H416V48c0-26.5-21.5-48-48-48H48zM416 160h50.7L544 237.3V256H416V160zM112 416a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm368-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg> <span><?php echo $_product->getAttributeText('shippingoption'); ?> Delivery</span></div>
                            <?php }*/ ?>
                                <?php echo $productImage->toHtml(); ?>

                        <?php /*if ($_product->getIsSalable()): ?>
                            <div class="stock available"><span><?php if(!empty($custom_stock_status)){ echo $custom_stock_status; } else { echo __('In stock'); } ?></span></div>
                        <?php endif;*/ ?>
                            <?php if($ship_opt=="Free"){ ?>
                                <div class="delivery-tag"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M48 0C21.5 0 0 21.5 0 48V368c0 26.5 21.5 48 48 48H64c0 53 43 96 96 96s96-43 96-96H384c0 53 43 96 96 96s96-43 96-96h32c17.7 0 32-14.3 32-32s-14.3-32-32-32V288 256 237.3c0-17-6.7-33.3-18.7-45.3L512 114.7c-12-12-28.3-18.7-45.3-18.7H416V48c0-26.5-21.5-48-48-48H48zM416 160h50.7L544 237.3V256H416V160zM112 416a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm368-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg> <span><?php echo $_product->getAttributeText('shippingoption'); ?> Delivery</span></div>
                            <?php } else { ?><div class="delivery-tag bg-white"></div><?php } ?>
                            </a>
                        </div>
                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                        <div class="hover-box">
                            <?php /*if($ship_opt=="Free"){ ?>
                                <div class="delivery-tag"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M48 0C21.5 0 0 21.5 0 48V368c0 26.5 21.5 48 48 48H64c0 53 43 96 96 96s96-43 96-96H384c0 53 43 96 96 96s96-43 96-96h32c17.7 0 32-14.3 32-32s-14.3-32-32-32V288 256 237.3c0-17-6.7-33.3-18.7-45.3L512 114.7c-12-12-28.3-18.7-45.3-18.7H416V48c0-26.5-21.5-48-48-48H48zM416 160h50.7L544 237.3V256H416V160zM112 416a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm368-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg> <span><?php echo $_product->getAttributeText('shippingoption'); ?> Delivery</span></div>
                            <?php }*/ ?>
                        <h2 class="product-name">
                            <a class="product-item-link" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                            <a class="detail_links" href="<?php echo $_product->getProductUrl() ?>" ></a>
                            <div class="product actions"<?php echo ($pos && strpos($pos, $viewMode . '-actions')) ? $position : ''; ?>>
                                <?php echo $block->getProductPrice($_product) ?>        
                                <?php if ($showCart): ?>
                                    <div class="actions-primary"<?php echo ($pos && strpos($pos, $viewMode . '-primary')) ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            
                                            <form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Shop Now')); ?>"
                                                        class="action tocart primary button btn-cart">
                                                        <i class="icon icon-add-to-cart"></i>
                                                        <span><?php echo __('Shop Now') ?>
                                                        </span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php if(!empty($custom_stock_status)){ echo $custom_stock_status; } else { echo __('In stock'); } ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo ($pos && strpos($pos, $viewMode . '-secondary')) ? $position : ''; ?>>
                                        <?php if ($showCompare):
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <i class="icon icon-compare"></i><?php echo __('Compare') ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <i class="icon icon-favorites"></i><?php echo __('Wishlist') ?>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                     <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                            </div>
                    <?php endif; ?>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php // echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
</div>
