<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<?php
$_order  = $block->getOrder();
$_source = $block->getSource();
$_fullInfo = $this->helper('Magento\Tax\Helper\Data')->getCalculatedTaxes($_source);
$code = 'tax';
?>
<?php $var = $block->getParentBlock()->getVarModel();?>

<tr>
    <td style="color: #707582; font-size: 14px; font-weight: bold;">
        <?php echo $block->escapeHtml(__('Tax')); ?>
    </td>
    <td width="15" height="25"  style="width: 15px !important; height: 25px">&nbsp;</td>
    <td style="color: #707582; font-size: 14px; text-align: right;" align="right">
        <?php echo $_order->formatPrice($_source->getTaxAmount()) ?>
    </td>
</tr>
