<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */
/** @var $block \Amasty\RequestQuote\Block\Account\Quote\Item\Price\Renderer
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getItem();
$price = $item->getHidePrice() ? $escaper->escapeHtml(__('N/A')) : $block->convertPrice($block->getOriginalPrice());
?>

<?= /* @noEscape */ $price ?>
