<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */

/** @var $block \Amasty\RequestQuote\Block\Account\Quote\Item\Price\Renderer */

$item = $block->getItem();
?>
<?= /* @noEscape */ $item->getNotes() && $item->getNotes()->getRequestedPrice()
    ? $block->convertPrice($item->getNotes()->getRequestedPrice(), true)
    : $escaper->escapeHtml(__('N/A'))
?>
