<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="main-footer">
	<div class="container">
		<?php echo $this->getChildHtml('main-footer'); ?>
	</div>
</div>
<div class="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-left">
				<div class="copyright">
					Copyright &copy; <?php echo date('Y'); ?> Speedy Street Solutions - All Rights Reserved.
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pull-right">
				<ul>
          <li><a href="/privacy-policy-cookie-restriction-mode">Privacy Policy</a></li>
        </ul>
			</div>
		</div>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>
<?php /* ?><div><div class="snowflake">
  ❅
  </div>
  <div class="snowflake">
  ❅
  </div>
  <div class="snowflake">
  ❆
  </div>
  <div class="snowflake">
  ❄
  </div>
  <div class="snowflake">
  ❅
  </div>
  <div class="snowflake">
  ❆
  </div>
  <div class="snowflake">
  ❄
  </div>
  <div class="snowflake">
  ❅
  </div>
  <div class="snowflake">
  ❆
  </div>
  <div class="snowflake">
  ❄
  </div></div><?php */ ?>
